### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by WUUUUTTT** [MattSurabian/proxpn-bash-client#42] opened 2016-07-27 01:54 UTC
Wondering if anyone else having this issue.  When I run a DNS leak test on https://www.dnsleaktest.com/ I show the ISP as level 3 and not a proxpn IP.  

Anyone else had this issue?

**Comment by MattSurabian** [comment] 2016-07-27 03:42
This is expected behavior in the sense that ProXPN's OpenVPN gateways don't push any `dhcp-options` to set the DNS servers on the client machine.

You can confirm this by looking at the tail end of the output when connecting:

```
Tue Jul 26 23:15:48 2016 us=526818 TUN/TAP device tun0 opened
Tue Jul 26 23:15:48 2016 us=526875 TUN/TAP TX queue length set to 100
Tue Jul 26 23:15:48 2016 us=526920 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Tue Jul 26 23:15:48 2016 us=526996 /sbin/ip link set dev tun0 up mtu 1500
Tue Jul 26 23:15:48 2016 us=532647 /sbin/ip addr add dev tun0 192.168.61.23/24 broadcast 192.168.61.255
Tue Jul 26 23:15:48 2016 us=535491 /sbin/ip route add 50.7.1.67/32 via 10.0.1.1
Tue Jul 26 23:15:48 2016 us=536486 /sbin/ip route del 0.0.0.0/0
Tue Jul 26 23:15:48 2016 us=537291 /sbin/ip route add 0.0.0.0/0 via 192.168.61.1
Tue Jul 26 23:15:48 2016 us=538066 Initialization Sequence Completed
```

When `dchp-options DNS` is configured on the server you'll see a line like this shortly before the routes are added:

```
dhcp-option DNS SOME_IP_ADDRESS
```

This is probably a good thing as it leaves DNS totally in the hands of the consumer instead of unexpectedly modifying client settings. Using the `dhcp-option`s method would also add the responsibility of ensuring a refresh of the new DNS settings on the client machine; a process which varies across operating systems.

To avoid DNS leakage I recommend you set your machine's DNS values explicitly, and for an additional layer of assurance set the immutable bit on the system's resolv.conf file (or equivalent) which prevents ANY modifications to the file by ALL users and processes regardless of what the mode of the file is: `chattr +i file_path`. Note that doing this may have unintended consequences, such as not being able to get automatically redirected to pay per access wifi hotspot purchase pages. To make the file mutable again according to it's mode unset the immutable bit: `chattr -i file_path`. Doing that ensures that you always know where your DNS traffc is going.

**Comment by MattSurabian** [comment] 2016-07-28 14:37
I'm going to close this but feel free to reopen if you'd like to discuss further.

**Closed as completed by MattSurabian** 2016-07-28 14:37 UTC
